backend:
  name: github
  repo: NChaffard/nc3d-portfolio
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Articles"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Miniature", name: "thumbnail", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "projets"
    label: "Projets"
    folder: "src/content/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image de couverture", name: "thumbnail", widget: "image" }
      - { label: "Galerie d'images", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Projet mis en avant", name: "featured", widget: "boolean", default: false, required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }